channels:
  - conda-forge
  - cvxgrp
  - IBMDecisionOptimization
dependencies:
  - python>=3.6
  - pip>=19.0
  - COMPAS>=0.6.1
  - shapely
  - cvxopt
  - cvxpy
  - cplex
  - pip:
    - git+https://github.com/BlockResearchGroup/compas_tna.git#egg=compas_tna
    - git+https://github.com/BlockResearchGroup/compas_assembly.git#egg=compas_assembly
    - git+https://github.com/BlockResearchGroup/compas_rbe.git#egg=compas_rbe
